### ISSUE TITLE
APIs list result not centered

### ISSUE THREAD

**Issue by hyamero** [rutikwankhade/Apihouse#2]
![issuebadge](https://img.shields.io/badge/Issue-Responsiveness-dddddd?style=for-the-badge&labelColor=000000&logoWidth=15)
APIs list result is _not centered_. `justify-content: center` in the `flexed parent` might be an easy fix.

![issue2](https://user-images.githubusercontent.com/78056869/131965615-c689784d-1ff6-487a-b628-fcaf5ca13e43.jpg)

**Comment by rutikwankhade** [comment]
Hey @hyamero , Thanks for pointing it out. I fixed it now.
