### ISSUE TITLE
Regarding the current situation of the Public APIs project

### ISSUE THREAD

**Issue by pawelborkar** [rutikwankhade/Apihouse#3]
Hey @rutikwankhade ,
Hope your doing good. This issue is regarding the current situation which we the collaborators at [Public APIs](https://github.com/public-apis/public-apis/issues/3104) are facing  regarding the future of public apis and the open source community in general.

As we've added your website in one of the unofficial list of websites in the readme, there's a possibility of a number of people visiting it. So it's one of the reasons I'm writing this issue. In order to bring this issue in front of the community members  

Please read [this](https://github.com/public-apis/public-apis/issues/3104) issue and we would encourage you to spread it on your website's homepage or write blogs or a tweet about it in order to bring this serious issue into the limelight of the community members. And help the project to survive.

Thanks, 
Pawel

**Comment by rutikwankhade** [comment]
The public API project is a gem for the developer community. I have updated the homepage to spread awareness about the current situation. Hope it helps.
